name: GetInfo
main: net.yeticraft.squatingyeti.GetInfo.GetInfo
version: 1.0
description: >
             GetInfo
commands:
  getinfo: 
    description: gathers information of a player
    usage: /Getinfo